import Link from "next/link"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className="max-w-3xl mx-auto py-10">
        <header className="flex items-center justify-between">
          <Link href='/' className="bg-gradient-to-r from-orange-500 via-red-500 to-purple-600
    bg-clip-text text-transparent text-lg font-bold">RafaMS</Link>
        </header>
      <main className="py-10">{children}</main>
      </body>
    </html>
  )
}
